# application/notification_types.py
import enum

class NotificationType(enum.Enum):
    """Standard notification types for the Swiss Manager system."""
    WELCOME = "WELCOME"
    REGISTRATION_SUBMITTED = "REGISTRATION_SUBMITTED"
    REGISTRATION_APPROVED = "REGISTRATION_APPROVED"
    REGISTRATION_REJECTED = "REGISTRATION_REJECTED"
    ARBITER_INVITATION = "ARBITER_INVITATION"
    FIDE_VERIFICATION_APPROVED = "FIDE_VERIFICATION_APPROVED"
    FIDE_VERIFICATION_REJECTED = "FIDE_VERIFICATION_REJECTED"

    # Future types (not yet implemented in business logic)
    FIDE_RATING_UPDATED = "FIDE_RATING_UPDATED"
    TOURNAMENT_STARTED = "TOURNAMENT_STARTED"
    TOURNAMENT_FINISHED = "TOURNAMENT_FINISHED"
    PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED"
    ROUND_CREATED = "ROUND_CREATED"
    PAIRING_PUBLISHED = "PAIRING_PUBLISHED"