"""Add ref_id to PaymentModel

Revision ID: 28286d1b2bc2
Revises: fbbcf1faf888
Create Date: 2026-08-17 15:37:35.042564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28286d1b2bc2'
down_revision = 'fbbcf1faf888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_ref_id'), ['ref_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_ref_id'))
        batch_op.drop_column('ref_id')

    # ### end Alembic commands ###
