"""Phase 4A: Add PaymentModel

Revision ID: 2d225097e5f2
Revises: 8bbfd79d722c
Create Date: 2026-08-16 19:55:46.931287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d225097e5f2'
down_revision = '8bbfd79d722c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('authority', sa.String(length=100), nullable=True),
    sa.Column('card_mask', sa.String(length=20), nullable=True),
    sa.Column('gateway_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authority', name='uq_payment_authority'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_authority'), ['authority'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_registration_id'), ['registration_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_registration_id'))
        batch_op.drop_index(batch_op.f('ix_payments_authority'))

    op.drop_table('payments')
    # ### end Alembic commands ###
