"""add unique constraints

Revision ID: 627a4a3884fc
Revises: 37bc95a6a8d8
Create Date: 2026-07-11 00:42:04.194473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '627a4a3884fc'
down_revision = '37bc95a6a8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bye_requests', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_bye_tournament_player_round', ['tournament_id', 'player_id', 'for_round'])

    with op.batch_alter_table('pairings', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_pairing_round_board', ['round_id', 'board_number'])

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_player_tournament_startnum', ['tournament_id', 'start_number'])

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_round_tournament_number', ['tournament_id', 'round_number'])

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.alter_column('admin_code',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.alter_column('admin_code',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_constraint('uq_round_tournament_number', type_='unique')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('uq_player_tournament_startnum', type_='unique')

    with op.batch_alter_table('pairings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pairing_round_board', type_='unique')

    with op.batch_alter_table('bye_requests', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bye_tournament_player_round', type_='unique')

    # ### end Alembic commands ###
