"""Add bank transfer, rulebook and receipt fields

Revision ID: 7710e9d746d8
Revises: 447ba9345c5e
Create Date: 2026-08-17 16:26:09.388648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7710e9d746d8'
down_revision = '447ba9345c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('receipt_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_card_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rulebook_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('rulebook_text')
        batch_op.drop_column('bank_card_number')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('receipt_path')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
