"""Phase 8E: Add indexes for pairings

Revision ID: 82251659c3a2
Revises: b80e002e83f5
Create Date: 2026-08-20 23:51:36.288763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82251659c3a2'
down_revision = 'b80e002e83f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairings', schema=None) as batch_op:
        batch_op.create_index('ix_pairing_black_participant_id', ['black_participant_id'], unique=False)
        batch_op.create_index('ix_pairing_white_participant_id', ['white_participant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pairings', schema=None) as batch_op:
        batch_op.drop_index('ix_pairing_white_participant_id')
        batch_op.drop_index('ix_pairing_black_participant_id')

    # ### end Alembic commands ###
