"""Phase 3A: Add pricing fields to Tournament, PromoCode and Registration models

Revision ID: 8bbfd79d722c
Revises: be7894fdfe99
Create Date: 2026-08-16 13:52:35.080734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbfd79d722c'
down_revision = 'be7894fdfe99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_codes_code'), ['code'], unique=False)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('final_price', sa.Integer(), nullable=True),
    sa.Column('pricing_breakdown', sa.Text(), nullable=True),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'player_profile_id', name='uq_registration_tournament_profile'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('registration_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('max_players', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('early_bird_config', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('veteran_config', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('women_discount_percent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('title_discounts', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('title_discounts')
        batch_op.drop_column('women_discount_percent')
        batch_op.drop_column('veteran_config')
        batch_op.drop_column('early_bird_config')
        batch_op.drop_column('max_players')
        batch_op.drop_column('registration_deadline')
        batch_op.drop_column('base_price')

    op.drop_table('registrations')
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_codes_code'))

    op.drop_table('promo_codes')
    # ### end Alembic commands ###
