"""Add national id and bank card to profile

Revision ID: 9a7faf86965a
Revises: ddcd3bf5d952
Create Date: 2026-08-17 12:43:38.125321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7faf86965a'
down_revision = 'ddcd3bf5d952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('bank_card_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bank_account_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.drop_column('bank_account_name')
        batch_op.drop_column('bank_card_number')
        batch_op.drop_column('national_id')

    # ### end Alembic commands ###
