"""Add rejection reason to RegistrationModel

Revision ID: b80e002e83f5
Revises: 7710e9d746d8
Create Date: 2026-08-17 16:58:31.437597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80e002e83f5'
down_revision = '7710e9d746d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')

    # ### end Alembic commands ###
