"""Fresh baseline schema for clean production deployment (Category K).

Single squashed migration representing the complete current db_models.py
schema. Supersedes the historical six-revision chain; no data preservation
is required for this deployment strategy.

Revision ID: bb0160eefd6b
Revises: 
Create Date: 2026-08-24 17:31:35.507657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0160eefd6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fide_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_imported', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('fide_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fide_imports_period'), ['period'], unique=False)

    op.create_table('fide_players',
    sa.Column('fide_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('federation', sa.String(length=5), nullable=True),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.Column('wtitle', sa.String(length=10), nullable=True),
    sa.Column('otitle', sa.String(length=10), nullable=True),
    sa.Column('foatitle', sa.String(length=10), nullable=True),
    sa.Column('birth_year', sa.String(length=4), nullable=True),
    sa.Column('inactive', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('fide_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('fide_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fide_players_federation'), ['federation'], unique=False)

    op.create_table('temp_import_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('temp_import_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temp_import_data_session_key'), ['session_key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('telegram_link_token', sa.String(length=100), nullable=True),
    sa.Column('telegram_link_expires_at', sa.DateTime(), nullable=True),
    sa.Column('bale_chat_id', sa.String(length=50), nullable=True),
    sa.Column('bale_link_token', sa.String(length=100), nullable=True),
    sa.Column('bale_link_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_bale_chat_id'), ['bale_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_telegram_chat_id'), ['telegram_chat_id'], unique=False)

    op.create_table('fide_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fide_id', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('rating_type', sa.String(length=10), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('k_factor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fide_id'], ['fide_players.fide_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fide_id', 'period', 'rating_type', name='uq_fide_rating_period_type'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('fide_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fide_ratings_fide_id'), ['fide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fide_ratings_period'), ['period'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferences_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_is_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('player_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fide_id', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('federation', sa.String(length=5), nullable=True),
    sa.Column('fide_title', sa.String(length=5), nullable=True),
    sa.Column('fide_verification_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('national_id', sa.String(length=10), nullable=True),
    sa.Column('bank_card_number', sa.String(length=20), nullable=True),
    sa.Column('bank_account_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('id_document_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_profiles_fide_id'), ['fide_id'], unique=False)

    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('federation', sa.String(length=5), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('time_control_type', sa.String(length=20), nullable=True),
    sa.Column('time_control_description', sa.String(length=100), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('chief_arbiter', sa.String(length=100), nullable=True),
    sa.Column('arbiter', sa.String(length=100), nullable=True),
    sa.Column('tiebreak_rules', sa.Text(), nullable=True),
    sa.Column('cumulative_age_category', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('bank_card_number', sa.String(length=20), nullable=True),
    sa.Column('bank_account_name', sa.String(length=100), nullable=True),
    sa.Column('bank_transfer_notes', sa.Text(), nullable=True),
    sa.Column('enable_online_payment', sa.Boolean(), nullable=True),
    sa.Column('rulebook_text', sa.Text(), nullable=True),
    sa.Column('rulebook_sections', sa.Text(), nullable=True),
    sa.Column('rulebook_pdf_path', sa.String(length=255), nullable=True),
    sa.Column('early_bird_config', sa.Text(), nullable=True),
    sa.Column('veteran_config', sa.Text(), nullable=True),
    sa.Column('women_discount_percent', sa.Integer(), nullable=True),
    sa.Column('title_discounts', sa.Text(), nullable=True),
    sa.Column('registration_requirements', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_public_id'), ['public_id'], unique=True)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('player_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_profile_id', sa.Integer(), nullable=False),
    sa.Column('requested_fide_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('player_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_verifications_player_profile_id'), ['player_profile_id'], unique=False)

    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_codes_code'), ['code'], unique=False)

    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'round_number', name='uq_round_tournament_number'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('tournament_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_profile_id', sa.Integer(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('pairing_no', sa.Integer(), nullable=True),
    sa.Column('rating_snapshot', sa.Integer(), nullable=True),
    sa.Column('fide_title_snapshot', sa.String(length=5), nullable=True),
    sa.Column('k_factor', sa.Integer(), nullable=True),
    sa.Column('age_category', sa.String(length=10), nullable=True),
    sa.Column('custom_category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('joined_from_round', sa.Integer(), nullable=True),
    sa.Column('withdrawn_at_round', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('color_history', sa.String(length=255), nullable=True),
    sa.Column('float_history', sa.String(length=255), nullable=True),
    sa.Column('received_bye', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'player_profile_id', name='uq_participant_tournament_profile'),
    sa.UniqueConstraint('tournament_id', 'start_number', name='uq_participant_tournament_startnum'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('tournament_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'user_id', name='uq_tournament_staff'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('bye_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('bye_type', sa.String(length=10), nullable=True),
    sa.Column('for_round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['tournament_participants.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'participant_id', 'for_round', name='uq_bye_tournament_participant_round'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('manual_pairings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('white_participant_id', sa.Integer(), nullable=False),
    sa.Column('black_participant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['black_participant_id'], ['tournament_participants.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['white_participant_id'], ['tournament_participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'round_number', 'black_participant_id', name='uq_manual_pairing_black'),
    sa.UniqueConstraint('tournament_id', 'round_number', 'white_participant_id', name='uq_manual_pairing_white'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('pairings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('board_number', sa.Integer(), nullable=False),
    sa.Column('white_participant_id', sa.Integer(), nullable=True),
    sa.Column('black_participant_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('white_float', sa.String(length=1), nullable=True),
    sa.Column('black_float', sa.String(length=1), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['black_participant_id'], ['tournament_participants.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['white_participant_id'], ['tournament_participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'board_number', name='uq_pairing_round_board'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('pairings', schema=None) as batch_op:
        batch_op.create_index('ix_pairing_black_participant_id', ['black_participant_id'], unique=False)
        batch_op.create_index('ix_pairing_white_participant_id', ['white_participant_id'], unique=False)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('final_price', sa.Integer(), nullable=True),
    sa.Column('pricing_breakdown', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('receipt_path', sa.String(length=255), nullable=True),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'player_profile_id', name='uq_registration_tournament_profile'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('authority', sa.String(length=100), nullable=True),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('card_mask', sa.String(length=20), nullable=True),
    sa.Column('gateway_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authority', name='uq_payment_authority'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_authority'), ['authority'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_ref_id'), ['ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_registration_id'), ['registration_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_registration_id'))
        batch_op.drop_index(batch_op.f('ix_payments_ref_id'))
        batch_op.drop_index(batch_op.f('ix_payments_authority'))

    op.drop_table('payments')
    op.drop_table('registrations')
    with op.batch_alter_table('pairings', schema=None) as batch_op:
        batch_op.drop_index('ix_pairing_white_participant_id')
        batch_op.drop_index('ix_pairing_black_participant_id')

    op.drop_table('pairings')
    op.drop_table('manual_pairings')
    op.drop_table('bye_requests')
    op.drop_table('tournament_staff')
    op.drop_table('tournament_participants')
    op.drop_table('rounds')
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_codes_code'))

    op.drop_table('promo_codes')
    with op.batch_alter_table('player_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_verifications_player_profile_id'))

    op.drop_table('player_verifications')
    op.drop_table('user_roles')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_public_id'))

    op.drop_table('tournaments')
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_profiles_fide_id'))

    op.drop_table('player_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index('ix_notification_user_is_read')

    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('fide_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fide_ratings_period'))
        batch_op.drop_index(batch_op.f('ix_fide_ratings_fide_id'))

    op.drop_table('fide_ratings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_chat_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_bale_chat_id'))

    op.drop_table('users')
    with op.batch_alter_table('temp_import_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temp_import_data_session_key'))

    op.drop_table('temp_import_data')
    with op.batch_alter_table('fide_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fide_players_federation'))

    op.drop_table('fide_players')
    with op.batch_alter_table('fide_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fide_imports_period'))

    op.drop_table('fide_imports')
    # ### end Alembic commands ###
