"""Phase 1A

Revision ID: be7894fdfe99
Revises: 
Create Date: 2026-08-16 00:01:32.164641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be7894fdfe99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fide_players',
    sa.Column('fide_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('federation', sa.String(length=5), nullable=True),
    sa.Column('fide_title', sa.String(length=5), nullable=True),
    sa.Column('rating_standard', sa.Integer(), nullable=True),
    sa.Column('rating_rapid', sa.Integer(), nullable=True),
    sa.Column('rating_blitz', sa.Integer(), nullable=True),
    sa.Column('birth_year', sa.String(length=4), nullable=True),
    sa.Column('k_factor', sa.Integer(), nullable=True),
    sa.Column('dataset_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('fide_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('fide_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fide_players_last_name'), ['last_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('player_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fide_id', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('federation', sa.String(length=5), nullable=True),
    sa.Column('fide_title', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_profiles_fide_id'), ['fide_id'], unique=False)

    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=8), nullable=False),
    sa.Column('admin_code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('federation', sa.String(length=5), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('time_control_type', sa.String(length=20), nullable=True),
    sa.Column('time_control_description', sa.String(length=100), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('chief_arbiter', sa.String(length=100), nullable=True),
    sa.Column('arbiter', sa.String(length=100), nullable=True),
    sa.Column('tiebreak_rules', sa.Text(), nullable=True),
    sa.Column('cumulative_age_category', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_public_id'), ['public_id'], unique=True)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'round_number', name='uq_round_tournament_number'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('tournament_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('player_profile_id', sa.Integer(), nullable=False),
    sa.Column('start_number', sa.Integer(), nullable=False),
    sa.Column('pairing_no', sa.Integer(), nullable=True),
    sa.Column('rating_snapshot', sa.Integer(), nullable=True),
    sa.Column('fide_title_snapshot', sa.String(length=5), nullable=True),
    sa.Column('k_factor', sa.Integer(), nullable=True),
    sa.Column('age_category', sa.String(length=10), nullable=True),
    sa.Column('custom_category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('joined_from_round', sa.Integer(), nullable=True),
    sa.Column('withdrawn_at_round', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('color_history', sa.String(length=255), nullable=True),
    sa.Column('float_history', sa.String(length=255), nullable=True),
    sa.Column('received_bye', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'player_profile_id', name='uq_participant_tournament_profile'),
    sa.UniqueConstraint('tournament_id', 'start_number', name='uq_participant_tournament_startnum'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('bye_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('bye_type', sa.String(length=10), nullable=True),
    sa.Column('for_round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['tournament_participants.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'participant_id', 'for_round', name='uq_bye_tournament_participant_round'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('manual_pairings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('white_participant_id', sa.Integer(), nullable=False),
    sa.Column('black_participant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['black_participant_id'], ['tournament_participants.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['white_participant_id'], ['tournament_participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'round_number', 'black_participant_id', name='uq_manual_pairing_black'),
    sa.UniqueConstraint('tournament_id', 'round_number', 'white_participant_id', name='uq_manual_pairing_white'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('pairings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('board_number', sa.Integer(), nullable=False),
    sa.Column('white_participant_id', sa.Integer(), nullable=True),
    sa.Column('black_participant_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('white_float', sa.String(length=1), nullable=True),
    sa.Column('black_float', sa.String(length=1), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['black_participant_id'], ['tournament_participants.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['white_participant_id'], ['tournament_participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'board_number', name='uq_pairing_round_board'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pairings')
    op.drop_table('manual_pairings')
    op.drop_table('bye_requests')
    op.drop_table('tournament_participants')
    op.drop_table('rounds')
    op.drop_table('user_roles')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_public_id'))

    op.drop_table('tournaments')
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_profiles_fide_id'))

    op.drop_table('player_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('fide_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fide_players_last_name'))

    op.drop_table('fide_players')
    # ### end Alembic commands ###
