"""Add invitation system to TournamentStaffModel

Revision ID: ed74ec5e4f01
Revises: 9a7faf86965a
Create Date: 2026-08-17 12:54:20.049638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed74ec5e4f01'
down_revision = '9a7faf86965a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('invited_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['invited_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_staff', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invited_by')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
